name: Build and Run Frontend with pnpm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Sử dụng phiên bản 18.x vì Next.js 15.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm' # Cấu hình cache cho pnpm

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8 # Sử dụng phiên bản pnpm mới nhất

    - name: Add pnpm to PATH
      run: echo "$HOME/.pnpm" >> $GITHUB_PATH

    - name: Install dependencies
      run: pnpm install
      working-directory: ./frontend

    - name: Build frontend
      run: pnpm run build
      working-directory: ./frontend

    - name: Run tests
      run: pnpm test --if-present
      working-directory: ./frontend
